/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 wave.glb -T 
Files: wave.glb [150.14KB] > C:\mern stack\portfolio\3d-portfolio\public\models\wave-transformed.glb [145.66KB] (3%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Contactwave(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/wave-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <group name="Hips" position={[0, 1.021, 0]} rotation={[0.032, 0, 0]}>
            <group name="Spine" position={[0, 0.099, 0]} rotation={[-0.137, 0, 0]}>
              <group name="Spine1" position={[0, 0.13, 0]} rotation={[-0.064, 0, 0]}>
                <group name="Spine2" position={[0, 0.122, 0]} rotation={[0.094, 0, 0]}>
                  <group name="Neck" position={[0, 0.156, 0]} rotation={[0.409, 0, 0]}>
                    <group name="Head" position={[0, 0.123, 0]} rotation={[-0.327, 0, 0]}>
                      <group name="HeadTop_End" position={[0, 0.226, 0.037]} rotation={[-0.007, 0, 0]}>
                        <group name="HeadTop_End_end" position={[0, 0.124, 0]} />
                      </group>
                      <group name="LeftEye" position={[0.03, 0.088, 0.082]} rotation={[-0.007, 0, 0]}>
                        <group name="LeftEye_end" position={[0, 0.124, 0]} />
                      </group>
                      <group name="RightEye" position={[-0.03, 0.088, 0.082]} rotation={[-0.007, 0, 0]}>
                        <group name="RightEye_end" position={[0, 0.124, 0]} />
                      </group>
                    </group>
                  </group>
                  <group name="LeftShoulder" position={[0.047, 0.141, -0.006]} rotation={[1.559, 0.158, -1.563]}>
                    <group name="LeftArm" position={[0, 0.119, 0]} rotation={[0.158, 0.055, -0.008]}>
                      <group name="LeftForeArm" position={[0, 0.285, 0]} rotation={[0, 0.048, 0]}>
                        <group name="LeftHand" position={[0, 0.252, 0]} rotation={[0.036, 0.212, -0.099]}>
                          <group name="LeftHandThumb1" position={[-0.032, 0.026, 0.005]} rotation={[0.308, 0.115, 0.657]}>
                            <group name="LeftHandThumb2" position={[0, 0.041, 0]} rotation={[0, -0.154, 0]}>
                              <group name="LeftHandThumb3" position={[0, 0.031, 0]} rotation={[0, -0.05, 0]}>
                                <group name="LeftHandThumb4" position={[0, 0.035, 0]} rotation={[0.027, 0.105, -0.015]}>
                                  <group name="LeftHandThumb4_end" position={[0, 0.035, 0]} />
                                </group>
                              </group>
                            </group>
                          </group>
                          <group name="LeftHandIndex1" position={[-0.035, 0.098, -0.007]} rotation={[-0.024, -0.115, 0.092]}>
                            <group name="LeftHandIndex2" position={[0, 0.045, 0]} rotation={[0, -0.012, 0]}>
                              <group name="LeftHandIndex3" position={[0, 0.028, 0]} rotation={[0, -0.152, 0]}>
                                <group name="LeftHandIndex4" position={[0, 0.034, 0]} rotation={[0.091, 0.113, -0.019]}>
                                  <group name="LeftHandIndex4_end" position={[0, 0.034, 0]} />
                                </group>
                              </group>
                            </group>
                          </group>
                          <group name="LeftHandMiddle1" position={[-0.009, 0.1, -0.004]} rotation={[-0.022, -0.14, 0.092]}>
                            <group name="LeftHandMiddle2" position={[0, 0.046, 0]} rotation={[0, -0.02, 0]}>
                              <group name="LeftHandMiddle3" position={[0, 0.035, 0]} rotation={[0, -0.046, 0]}>
                                <group name="LeftHandMiddle4" position={[0, 0.035, 0]} rotation={[0.048, 0.045, -0.004]}>
                                  <group name="LeftHandMiddle4_end" position={[0, 0.035, 0]} />
                                </group>
                              </group>
                            </group>
                          </group>
                          <group name="LeftHandRing1" position={[0.015, 0.096, 0.002]} rotation={[-0.024, -0.116, 0.092]}>
                            <group name="LeftHandRing2" position={[0, 0.042, 0]} rotation={[0, -0.033, 0]}>
                              <group name="LeftHandRing3" position={[0, 0.036, 0]} rotation={[0, -0.012, 0]}>
                                <group name="LeftHandRing4" position={[0, 0.03, 0]} rotation={[0.014, -0.013, 0.044]}>
                                  <group name="LeftHandRing4_end" position={[0, 0.03, 0]} />
                                </group>
                              </group>
                            </group>
                          </group>
                          <group name="LeftHandPinky1" position={[0.039, 0.09, 0.01]} rotation={[-0.021, -0.151, 0.093]}>
                            <group name="LeftHandPinky2" position={[0, 0.028, 0]} rotation={[0, -0.429, 0]}>
                              <group name="LeftHandPinky3" position={[0, 0.022, 0]} rotation={[0, -0.024, 0]}>
                                <group name="LeftHandPinky4" position={[0, 0.026, 0]} rotation={[0.283, 0.204, -0.054]}>
                                  <group name="LeftHandPinky4_end" position={[0, 0.026, 0]} />
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="RightShoulder" position={[-0.047, 0.141, -0.006]} rotation={[1.559, -0.158, 1.563]}>
                    <group name="RightArm" position={[0, 0.119, 0]} rotation={[0.158, -0.055, 0.008]}>
                      <group name="RightForeArm" position={[0, 0.285, 0]} rotation={[0, -0.048, 0]}>
                        <group name="RightHand" position={[0, 0.252, 0]} rotation={[0.036, -0.212, 0.099]}>
                          <group name="RightHandThumb1" position={[0.032, 0.026, 0.005]} rotation={[0.308, -0.115, -0.657]}>
                            <group name="RightHandThumb2" position={[0, 0.041, 0]} rotation={[0, 0.154, 0]}>
                              <group name="RightHandThumb3" position={[0, 0.031, 0]} rotation={[0, 0.05, 0]}>
                                <group name="RightHandThumb4" position={[0, 0.035, 0]} rotation={[0.027, -0.105, 0.015]}>
                                  <group name="RightHandThumb4_end" position={[0, 0.035, 0]} />
                                </group>
                              </group>
                            </group>
                          </group>
                          <group name="RightHandIndex1" position={[0.035, 0.097, -0.007]} rotation={[-0.024, 0.115, -0.092]}>
                            <group name="RightHandIndex2" position={[0, 0.045, 0]} rotation={[0, 0.012, 0]}>
                              <group name="RightHandIndex3" position={[0, 0.028, 0]} rotation={[0, 0.152, 0]}>
                                <group name="RightHandIndex4" position={[0, 0.034, 0]} rotation={[0.091, -0.113, 0.019]}>
                                  <group name="RightHandIndex4_end" position={[0, 0.034, 0]} />
                                </group>
                              </group>
                            </group>
                          </group>
                          <group name="RightHandMiddle1" position={[0.009, 0.1, -0.003]} rotation={[-0.022, 0.14, -0.092]}>
                            <group name="RightHandMiddle2" position={[0, 0.046, 0]} rotation={[0, 0.02, 0]}>
                              <group name="RightHandMiddle3" position={[0, 0.035, 0]} rotation={[0, 0.046, 0]}>
                                <group name="RightHandMiddle4" position={[0, 0.035, 0]} rotation={[0.048, -0.045, 0.004]}>
                                  <group name="RightHandMiddle4_end" position={[0, 0.035, 0]} />
                                </group>
                              </group>
                            </group>
                          </group>
                          <group name="RightHandRing1" position={[-0.015, 0.096, 0.002]} rotation={[-0.024, 0.116, -0.092]}>
                            <group name="RightHandRing2" position={[0, 0.042, 0]} rotation={[0, 0.033, 0]}>
                              <group name="RightHandRing3" position={[0, 0.036, 0]} rotation={[0, 0.012, 0]}>
                                <group name="RightHandRing4" position={[0, 0.03, 0]} rotation={[0.014, 0.014, -0.044]}>
                                  <group name="RightHandRing4_end" position={[0, 0.03, 0]} />
                                </group>
                              </group>
                            </group>
                          </group>
                          <group name="RightHandPinky1" position={[-0.039, 0.09, 0.011]} rotation={[-0.021, 0.151, -0.093]}>
                            <group name="RightHandPinky2" position={[0, 0.028, 0]} rotation={[0, 0.429, 0]}>
                              <group name="RightHandPinky3" position={[0, 0.022, 0]} rotation={[0, 0.024, 0]}>
                                <group name="RightHandPinky4" position={[0, 0.026, 0]} rotation={[0.283, -0.204, 0.054]}>
                                  <group name="RightHandPinky4_end" position={[0, 0.026, 0]} />
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
            <group name="LeftUpLeg" position={[0.095, 0.005, -0.003]} rotation={[-0.019, -0.004, -3.139]}>
              <group name="LeftLeg" position={[0, 0.458, 0]} rotation={[-0.083, 0, -0.006]}>
                <group name="LeftFoot" position={[0, 0.444, 0]} rotation={[1.063, 0.082, 0.022]}>
                  <group name="LeftToeBase" position={[0, 0.149, 0]} rotation={[0.546, -0.074, 0.059]}>
                    <group name="LeftToe_End" position={[0, 0.099, 0]} rotation={[-0.546, 1.542, 0.581]}>
                      <group name="LeftToe_End_end" position={[0, 0.099, 0]} />
                    </group>
                  </group>
                </group>
              </group>
            </group>
            <group name="RightUpLeg" position={[-0.095, 0.005, -0.003]} rotation={[-0.019, 0.004, 3.139]}>
              <group name="RightLeg" position={[0, 0.458, 0]} rotation={[-0.083, 0, 0.006]}>
                <group name="RightFoot" position={[0, 0.444, 0]} rotation={[1.063, -0.082, -0.022]}>
                  <group name="RightToeBase" position={[0, 0.149, 0]} rotation={[0.546, 0.074, -0.059]}>
                    <group name="RightToe_End" position={[0, 0.099, 0]} rotation={[-0.547, -1.542, -0.582]}>
                      <group name="RightToe_End_end" position={[0, 0.099, 0]} />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/wave-transformed.glb')
